/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 /Users/emiliehopkinson/Desktop/Thesis/layered/public/animated/animated_cylinder.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'

const AnimatedCylinder = (props) => {
  const { nodes, animations } = useGLTF('/animated/animated_cylinder.glb')
  const { actions } = useAnimations(animations);

  console.log(animations);
  console.log(actions);

  
  useEffect (() => {
    console.log(actions)
    // actions.CylinderAction.play()
  }, [actions]);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} position={[0, -0.036, 0]} />
    </group>
  )
}

useGLTF.preload('/animated/animated_cylinder.glb')

export default AnimatedCylinder;