/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/3dAssets/fairyScene.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


const FairyScene = (props) => {
  const { nodes, materials } = useGLTF('/3dAssets/fairyScene.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} position={[0, 14.496, -11.329]} rotation={[Math.PI / 2, 0, 0]} scale={[42.029, 1, 26.827]} />
      <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} position={[-10.768, 13.576, -5.669]} rotation={[Math.PI / 2, 0, 0]} scale={[11.164, 1, 7.126]} />
      <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} position={[9.54, 13.849, -5.669]} rotation={[Math.PI / 2, 0, 0]} scale={[7.313, 1, 4.668]} />
      <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} position={[1.424, 5.892, 3.491]} rotation={[Math.PI / 2, 0, 0]} scale={[6.789, 1, 8.271]} />
      <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} position={[-1.164, 8.972, 0.506]} rotation={[Math.PI / 2, 0, 0]} scale={[31.465, 1, 17.922]} />
      <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} position={[-4.18, 4.485, 7.134]} rotation={[Math.PI / 2, 0, 0]} scale={[6.15, 1, 9.515]} />
      <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} position={[7.411, 5.195, 6.34]} rotation={[Math.PI / 2, 0, 0]} scale={[7.954, 1, 10.55]} />
      <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} scale={[41.218, 1, 41.218]} />
      <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} position={[0.084, 4.642, 0.138]} rotation={[Math.PI / 2, 0, 0]} scale={[6.733, 1, 7.815]} />
      <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} position={[-11.948, 5.942, 4.782]} rotation={[Math.PI / 2, 0, 0]} scale={[13.79, 1, 18.29]} />
      <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} position={[11.852, 5.942, 4.782]} rotation={[Math.PI / 2, 0, 0]} scale={[13.79, 1, 18.29]} />
      <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} position={[8.927, 2.784, 9.935]} rotation={[Math.PI / 2, 0, 0]} scale={[9.338, 1, 12.386]} />
      <mesh geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} position={[-8.907, 2.784, 9.935]} rotation={[Math.PI / 2, 0, 0]} scale={[9.338, 1, 12.386]} />
    </group>
  )
}


useGLTF.preload('/3dAssets/fairyScene.glb');

export default FairyScene;
