/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/3dAssets/man.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Man = (props) => {
  const { nodes, materials } = useGLTF('/3dAssets/man.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bo_te01.geometry} material={nodes.Bo_te01.material} />
    </group>
  )
}

useGLTF.preload('/3dAssets/man.gltf')

export default Man;