/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/3dAssets/MyMountains.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Mountains = (props) => {

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3dAssets/MyMountains.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="defaultScene">
        <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} position={[0, 2.767, 0]} scale={[35.846, 8.407, 35.846]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dAssets/MyMountains.glb')


export default Mountains;