/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 /Users/emiliehopkinson/Desktop/Thesis/layered/public/3dAssets/baked_pivots/plane.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/plane.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} position={[0, 0.5, 0]} rotation={[0, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/plane.glb')
