/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/3dAssets/test_flower.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { useLoader } from '@react-three/fiber'
import { MeshStandardMaterial } from 'three'

const SimpleFlower = (props) => {
  const { nodes, materials } = useGLTF('/3dAssets/test_flower.gltf');
  const colorMap = useLoader(TextureLoader, 'https://images.101cookbooks.com/edible_flowers.jpg?w=1200&auto=compress&auto=format');

    // Create a material with the loaded texture
    const textureMaterial = new MeshStandardMaterial({
      map: colorMap,
    });

  return (
    <group {...props} dispose={null} scale={0.1} position={[0.0, -4.0, 0.0]}>


      <mesh geometry={nodes.stem.geometry} >
          <meshStandardMaterial color={'green'}/>
      </mesh>


      <mesh geometry={nodes.pollen_flower.geometry}>
        <meshStandardMaterial color={'yellow'}/>
      </mesh>

      <mesh>

        <mesh geometry={nodes.flower_pSphere10_flower_petal_set_1.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.flower_flower_petal_set_1_pSphere9.geometry}  />
        <mesh geometry={nodes.flower_flower_petal_set_1_pSphere8.geometry}  />
        <mesh geometry={nodes.flower_flower_petal_set_1_pSphere7.geometry}  />
        <mesh geometry={nodes.flower_flower_petal_set_1_pSphere6.geometry}  />
        <mesh geometry={nodes.flower_flower_petal_set_1_pSphere5.geometry}  />
        <mesh geometry={nodes.flower_flower_petal_set_1_pSphere4.geometry}  />
        <mesh geometry={nodes.flower_flower_petal_set_1_pSphere3.geometry}  />
        <mesh geometry={nodes.flower_pasted__pSphere10_pasted__flower_petal_set_1_flower_pet_set_3.geometry} />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_3_pasted__pSphere9.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_3_pasted__pSphere8.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_3_pasted__pSphere7.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_3_pasted__pSphere6.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_3_pasted__pSphere5.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_3_pasted__pSphere4.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_3_pasted__pSphere3.geometry}  />
        <mesh geometry={nodes.flower_pasted__pSphere10_pasted__flower_petal_set_1_flower_pet_set_2.geometry} />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_2_pasted__pSphere9.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_2_pasted__pSphere8.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_2_pasted__pSphere7.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_2_pasted__pSphere6.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_2_pasted__pSphere5.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_2_pasted__pSphere3.geometry}  />
        <mesh geometry={nodes.flower_pasted__flower_petal_set_1_flower_pet_set_2_pasted__pSphere4.geometry}  />

      </mesh>



      
    </group>
  )
}

useGLTF.preload('/3dAssets/test_flower.gltf')

export default SimpleFlower;