/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 public/3dAssets/walls.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Walls = (props) => {
  const { nodes, materials } = useGLTF('/3dAssets/walls.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} position={[0, 3.468, 0]} scale={[6.461, 1.496, 6.461]} />
    </group>
  )
}

useGLTF.preload('/3dAssets/walls.glb')
export default Walls;
